### ISSUE TITLE
Problems that may occur during runtime

### ISSUE THREAD

**Issue by lsrami** [voidful/wav2vec-u-exp#1]
**Here I want to record some of the problems I encountered when running this project, hoping to be helpful to those who follow:**

<br/>

- The first question is: 
  
  when you pull the docker image for the first time, you need to clean up the cache under /workspace/data/ (First, you need to make sure that* /workspace/data/librisample/sentence.txt* exist. Then , delete */workspace/data/test_ds/ *), otherwise you may encounter the following problems.

```sh
#Prepare text data
HYDRA_FULL_ERROR=1 zsh $FAIRSEQ_ROOT/examples/wav2vec/unsupervised/scripts/prepare_text.sh en /workspace/data/librisample/sentence.txt /workspace/data/test_ds/ 0 espeak-ng ./lid.176.bin
```

```sh
#Error FileExistsError: /workspace/data/test_ds/dict.txt
en
en-us
/workspace/data/librisample/sentence.txt
/workspace/data/test_ds/
min phone seen threshold is 0
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
2021-08-16 10:16:51 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, azureml_logging=False, bf16=False, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='/workspace/data/test_ds/', dict_only=True, empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, on_cpu_convert_precision=False, only_source=True, optimizer=None, padding_factor=1, plasma_path='/tmp/plasma', profile=False, quantization_config_path=None, reset_logging=False, scoring='bleu', seed=1, simul_type=None, source_lang=None, srcdict=None, suppress_crashes=False, target_lang=None, task='translation', tensorboard_logdir=None, testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=2, thresholdtgt=0, tokenizer=None, tpu=False, trainpref='/workspace/data/test_ds//lm.upper.lid.txt', use_plasma_view=False, user_dir=None, validpref=None, wandb_project=None, workers=1)
Traceback (most recent call last):
  File "/workspace/project/fairseq//fairseq_cli/preprocess.py", line 407, in <module>
    cli_main()
  File "/workspace/project/fairseq//fairseq_cli/preprocess.py", line 403, in cli_main
    main(args)
  File "/workspace/project/fairseq//fairseq_cli/preprocess.py", line 74, in main
    raise FileExistsError(dict_path(args.source_lang))
FileExistsError: /workspace/data/test_ds/dict.txt
```

```sh
#Solution

First, you need to make sure that /workspace/data/librisample/sentence.txt exist.
Then, delete /workspace/data/test_ds/ and run it again, it should be fine.
```

- The second question is:
When executing the running training script, a memory error may occur. The solution is to add *CUDA_LAUNCH_BLOCKING=1* when running the script.

```sh
#training script,
PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#Error RuntimeError: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 87, in forward
    logging_output[lk] = float(net_output[lk])
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

```sh
#Solution
CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

<br/>

- The third question is:
A cudnn error occurred when running the training script.

```sh
#training script
CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#Error RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 50, in forward
    net_output = model(**sample["net_input"])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 594, in forward
    grad_pen = self.calc_gradient_penalty(token_x, dense_x)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 379, in calc_gradient_penalty
    gradients = autograd.grad(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
root@9923932ef97d:/workspace/data# 

```

```sh
#Solution
vim /workspace/project/fairseq/fairseq_cli/hydra_train.py
#Paste the content below to line 76
torch.backends.cudnn.enabled = False #close cudnn

```

- Question four is:
Problems during training

```sh
#training script

CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 50, in forward
    net_output = model(**sample["net_input"])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 594, in forward
    grad_pen = self.calc_gradient_penalty(token_x, dense_x)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 379, in calc_gradient_penalty
    gradients = autograd.grad(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([24, 65, 1, 68], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(65, 384, kernel_size=[1, 6], padding=[0, 5], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 5, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f45b00fe100
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 65, 1, 68, 
    strideA = 4420, 68, 68, 1, 
output: TensorDescriptor 0x7f45b00fc000
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 384, 1, 73, 
    strideA = 28032, 73, 73, 1, 
weight: FilterDescriptor 0x7f45b010eb30
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 384, 65, 1, 6, 
Pointer addresses: 
    input: 0x7f4572ccf400
    output: 0x7f4592000000
    weight: 0x7f45c1000000
Additional pointer addresses: 
    grad_output: 0x7f4592000000
    grad_input: 0x7f4572ccf400
Backward data algorithm: 1

```

```sh
#Solution

vim /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan/w2vu.yaml
#Adjust batch_size
#For example: batch_size=64
```

**The above questions 2, 3, and 4 may all be GPU issues, so it is very important to ensure that your GPU driver version is correct.
In addition, I am very grateful to the author for his help.**

**Comment by cdleong** [comment]
Thank you very much for posting this! 

https://xkcd.com/979/ has been averted. :D

**Comment by lsrami** [comment]
> 
@cdleong 
Hello, have you completed the realization of the wav2vec-u project? I have completed the entire process in this docker environment, but currently my WER is very high. I find it difficult to converge using this docker environment for training. Do you have any good suggestions?

**Comment by duj12** [comment]
I meet the same problem in wav2vec-U training. If you use CPU to train, it's easy to debug this issue. In my case, I use w2vu2.yaml, the default parameter "target_dim" in wav2vec_u.py is 64 (and model.target_dim in w2vu2,yaml is also 64), which is different to the   number of my kmeans cluster label(aux_target in training).
I didn't try w2vu.yaml, but i think the problem may be similar. You can try to use CPU to train in debug mode.
